# Generated by Django 5.0.3 on 2024-03-26 16:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="department",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Введи имя", max_length=50, verbose_name="Имя"
                    ),
                ),
                (
                    "letter",
                    models.CharField(
                        help_text="Введи имя",
                        max_length=10,
                        verbose_name="Буква отделения",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="debtors",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "surname",
                    models.CharField(
                        help_text="Введи фамилию", max_length=30, verbose_name="Фамилия"
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Введи имя", max_length=30, verbose_name="Имя"
                    ),
                ),
                (
                    "lastname",
                    models.CharField(
                        help_text="Введи отчество",
                        max_length=30,
                        verbose_name="Отчество",
                    ),
                ),
                (
                    "date_birth",
                    models.DateField(
                        help_text="Введи дату рождения", verbose_name="Дата рождения"
                    ),
                ),
                (
                    "place_birth",
                    models.TextField(
                        help_text="Введи место рождения", verbose_name="Место рождения"
                    ),
                ),
                (
                    "contract_number",
                    models.TextField(
                        help_text="Введи номер договора", verbose_name="Номер договора"
                    ),
                ),
                (
                    "agreement_date",
                    models.DateField(
                        help_text="Введи дату договора", verbose_name="Дата договора"
                    ),
                ),
                (
                    "loan_amount",
                    models.FloatField(
                        help_text="Введи сумму займа", verbose_name="Сумма займа"
                    ),
                ),
                (
                    "interest",
                    models.FloatField(
                        default=0.0,
                        help_text="Считает автоматом",
                        verbose_name="Процент",
                    ),
                ),
                (
                    "state_duty",
                    models.FloatField(
                        default=0.0,
                        help_text="Считает автоматом",
                        verbose_name="Пошлина",
                    ),
                ),
                (
                    "total_amount",
                    models.FloatField(
                        default=0.0, help_text="Считает автоматом", verbose_name="Итого"
                    ),
                ),
                (
                    "department",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="mkk.department",
                        verbose_name="Подразделение",
                    ),
                ),
            ],
        ),
    ]
